/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopgcRouteImport } from './routes/shopgc'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChromeRouteImport } from './routes/chrome'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopgcRoute = ShopgcRouteImport.update({
  id: '/shopgc',
  path: '/shopgc',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeRoute = ChromeRouteImport.update({
  id: '/chrome',
  path: '/chrome',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chrome': typeof ChromeRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/receipt': typeof ReceiptRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/shopgc': typeof ShopgcRoute
  '/support': typeof SupportRoute
  '/sustainability': typeof SustainabilityRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/waitlist': typeof WaitlistRoute
  '/warranty': typeof WarrantyRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chrome': typeof ChromeRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/receipt': typeof ReceiptRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/shopgc': typeof ShopgcRoute
  '/support': typeof SupportRoute
  '/sustainability': typeof SustainabilityRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/waitlist': typeof WaitlistRoute
  '/warranty': typeof WarrantyRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chrome': typeof ChromeRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/receipt': typeof ReceiptRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/shopgc': typeof ShopgcRoute
  '/support': typeof SupportRoute
  '/sustainability': typeof SustainabilityRoute
  '/technology': typeof TechnologyRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRoute
  '/waitlist': typeof WaitlistRoute
  '/warranty': typeof WarrantyRoute
  '/products/$id': typeof ProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/chrome'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/privacy'
    | '/receipt'
    | '/shipping'
    | '/shop'
    | '/shopgc'
    | '/support'
    | '/sustainability'
    | '/technology'
    | '/terms'
    | '/track'
    | '/waitlist'
    | '/warranty'
    | '/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/chrome'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/privacy'
    | '/receipt'
    | '/shipping'
    | '/shop'
    | '/shopgc'
    | '/support'
    | '/sustainability'
    | '/technology'
    | '/terms'
    | '/track'
    | '/waitlist'
    | '/warranty'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/chrome'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/privacy'
    | '/receipt'
    | '/shipping'
    | '/shop'
    | '/shopgc'
    | '/support'
    | '/sustainability'
    | '/technology'
    | '/terms'
    | '/track'
    | '/waitlist'
    | '/warranty'
    | '/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ChromeRoute: typeof ChromeRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ReceiptRoute: typeof ReceiptRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  ShopgcRoute: typeof ShopgcRoute
  SupportRoute: typeof SupportRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TechnologyRoute: typeof TechnologyRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRoute
  WaitlistRoute: typeof WaitlistRoute
  WarrantyRoute: typeof WarrantyRoute
  ProductsIdRoute: typeof ProductsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopgc': {
      id: '/shopgc'
      path: '/shopgc'
      fullPath: '/shopgc'
      preLoaderRoute: typeof ShopgcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrome': {
      id: '/chrome'
      path: '/chrome'
      fullPath: '/chrome'
      preLoaderRoute: typeof ChromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ChromeRoute: ChromeRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ReceiptRoute: ReceiptRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  ShopgcRoute: ShopgcRoute,
  SupportRoute: SupportRoute,
  SustainabilityRoute: SustainabilityRoute,
  TechnologyRoute: TechnologyRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRoute,
  WaitlistRoute: WaitlistRoute,
  WarrantyRoute: WarrantyRoute,
  ProductsIdRoute: ProductsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
